name: plant
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.0
  image_picker: ^0.6.7
  camera: ^0.8.0
  http_parser: ^3.0.0
  dio: ^3.0.0
  dotted_border: ^1.0.7
  carousel_slider: ^3.0.0
  page_transition: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
